#include <map>
#include <string>

struct ArrlSectionInfo {
    std::string name;
    std::vector<int> dxcc_entities;
    std::string from_date;
    std::string deleted_date;
};

using ArrlSectionMap = std::map<std::string, ArrlSectionInfo>;

static const ArrlSectionMap ARRL_SECTION_MAP = {
    {"AL", {"Alabama", {291}, "", ""}},
    {"AK", {"Alaska", {6}, "", ""}},
    {"AB", {"Alberta", {1}, "", ""}},
    {"AR", {"Arkansas", {291}, "", ""}},
    {"AZ", {"Arizona", {291}, "", ""}},
    {"BC", {"British Columbia", {1}, "", ""}},
    {"CO", {"Colorado", {291}, "", ""}},
    {"CT", {"Connecticut", {291}, "", ""}},
    {"DE", {"Delaware", {291}, "", ""}},
    {"EB", {"East Bay", {291}, "", ""}},
    {"EMA", {"Eastern Massachusetts", {291}, "", ""}},
    {"ENY", {"Eastern New York", {291}, "", ""}},
    {"EPA", {"Eastern Pennsylvania", {291}, "", ""}},
    {"EWA", {"Eastern Washington", {291}, "", ""}},
    {"GA", {"Georgia", {291}, "", ""}},
    {"GH", {"Golden Horseshoe", {1}, "2023/01/01", ""}},
    {"GTA", {"Greater Toronto Area", {1}, "2012/09/01", "2023/01/01"}},
    {"ID", {"Idaho", {291}, "", ""}},
    {"IL", {"Illinois", {291}, "", ""}},
    {"IN", {"Indiana", {291}, "", ""}},
    {"IA", {"Iowa", {291}, "", ""}},
    {"KS", {"Kansas", {291}, "", ""}},
    {"KY", {"Kentucky", {291}, "", ""}},
    {"LAX", {"Los Angeles", {291}, "", ""}},
    {"LA", {"Louisiana", {291}, "", ""}},
    {"ME", {"Maine", {291}, "", ""}},
    {"MB", {"Manitoba", {1}, "", ""}},
    {"MAR", {"Maritime", {1}, "", "2023/01/01"}},
    {"MDC", {"Maryland-DC", {291}, "", ""}},
    {"MI", {"Michigan", {291}, "", ""}},
    {"MN", {"Minnesota", {291}, "", ""}},
    {"MS", {"Mississippi", {291}, "", ""}},
    {"MO", {"Missouri", {291}, "", ""}},
    {"MT", {"Montana", {291}, "", ""}},
    {"NE", {"Nebraska", {291}, "", ""}},
    {"NV", {"Nevada", {291}, "", ""}},
    {"NB", {"New Brunswick", {1}, "2023/01/01", ""}},
    {"NH", {"New Hampshire", {291}, "", ""}},
    {"NM", {"New Mexico", {291}, "", ""}},
    {"NLI", {"New York City-Long Island", {291}, "", ""}},
    {"NL", {"Newfoundland/Labrador", {1}, "", ""}},
    {"NC", {"North Carolina", {291}, "", ""}},
    {"ND", {"North Dakota", {291}, "", ""}},
    {"NTX", {"North Texas", {291}, "", ""}},
    {"NFL", {"Northern Florida", {291}, "", ""}},
    {"NNJ", {"Northern New Jersey", {291}, "", ""}},
    {"NNY", {"Northern New York", {291}, "", ""}},
    {"NT", {"Northwest Territories/Yukon/Nunavut", {1}, "2003/11/01", "2023/01/01"}},
    {"NWT", {"Northwest Territories/Yukon/Nunavut", {1}, "", "2003/11/01"}},
    {"NS", {"Nova Scotia", {1}, "2023/01/01", ""}},
    {"OH", {"Ohio", {291}, "", ""}},
    {"OK", {"Oklahoma", {291}, "", ""}},
    {"ON", {"Ontario", {1}, "", "2012/09/01"}},
    {"ONE", {"Ontario East", {1}, "2012/09/01", ""}},
    {"ONN", {"Ontario North", {1}, "2012/09/01", ""}},
    {"ONS", {"Ontario South", {1}, "2012/09/01", ""}},
    {"ORG", {"Orange", {291}, "", ""}},
    {"OR", {"Oregon", {291}, "", ""}},
    {"PAC", {"Pacific", {9, 20, 103, 110, 123, 138, 166, 174, 197, 297, 515}, "", ""}},
    {"PE", {"Prince Edward Island", {1}, "2020/04/01", ""}},
    {"PR", {"Puerto Rico", {43, 202}, "", ""}},
    {"QC", {"Quebec", {1}, "", ""}},
    {"RI", {"Rhode Island", {291}, "", ""}},
    {"SV", {"Sacramento Valley", {291}, "", ""}},
    {"SDG", {"San Diego", {291}, "", ""}},
    {"SF", {"San Francisco", {291}, "", ""}},
    {"SJV", {"San Joaquin Valley", {291}, "", ""}},
    {"SB", {"Santa Barbara", {291}, "", ""}},
    {"SCV", {"Santa Clara Valley", {291}, "", ""}},
    {"SK", {"Saskatchewan", {1}, "", ""}},
    {"SC", {"South Carolina", {291}, "", ""}},
    {"SD", {"South Dakota", {291}, "", ""}},
    {"STX", {"South Texas", {291}, "", ""}},
    {"SFL", {"Southern Florida", {291}, "", ""}},
    {"SNJ", {"Southern New Jersey", {291}, "", ""}},
    {"TN", {"Tennessee", {291}, "", ""}},
    {"TER", {"Territories", {1}, "2023/01/01", ""}},
    {"VI", {"US Virgin Islands", {105, 182, 285}, "", ""}},
    {"UT", {"Utah", {291}, "", ""}},
    {"VT", {"Vermont", {291}, "", ""}},
    {"VA", {"Virginia", {291}, "", ""}},
    {"WCF", {"West Central Florida", {291}, "", ""}},
    {"WTX", {"West Texas", {291}, "", ""}},
    {"WV", {"West Virginia", {291}, "", ""}},
    {"WMA", {"Western Massachusetts", {291}, "", ""}},
    {"WNY", {"Western New York", {291}, "", ""}},
    {"WPA", {"Western Pennsylvania", {291}, "", ""}},
    {"WWA", {"Western Washington", {291}, "", ""}},
    {"WI", {"Wisconsin", {291}, "", ""}},
    {"WY", {"Wyoming", {291}, "", ""}},
};