#ifndef DXCC_MAP_H_GENERATED_H
#define DXCC_MAP_H_GENERATED_H

// clang-format off

#include "CaseInsensitiveLess.h"

#include <vector>
#include <algorithm>

namespace ADIF {


struct DXCCEntity {
    std::string name;
    bool is_deleted;
};

using DXCCContainer = std::map<std::string, DXCCEntity, CaseInsensitiveLess>;

inline const DXCCContainer DXCC_MAP = {
        {"0", {"None (thecontacted stationis known to not be within a DXCC entity)", false}},
        {"1", {"CANADA", false}},
        {"2", {"ABU AIL IS.", true}},
        {"3", {"AFGHANISTAN", false}},
        {"4", {"AGALEGA & ST. BRANDON IS.", false}},
        {"5", {"ALAND IS.", false}},
        {"6", {"ALASKA", false}},
        {"7", {"ALBANIA", false}},
        {"8", {"ALDABRA", true}},
        {"9", {"AMERICAN SAMOA", false}},
        {"10", {"AMSTERDAM & ST. PAUL IS.", false}},
        {"11", {"ANDAMAN & NICOBAR IS.", false}},
        {"12", {"ANGUILLA", false}},
        {"13", {"ANTARCTICA", false}},
        {"14", {"ARMENIA", false}},
        {"15", {"ASIATIC RUSSIA", false}},
        {"16", {"NEW ZEALAND SUBANTARCTIC ISLANDS", false}},
        {"17", {"AVES I.", false}},
        {"18", {"AZERBAIJAN", false}},
        {"19", {"BAJO NUEVO", true}},
        {"20", {"BAKER & HOWLAND IS.", false}},
        {"21", {"BALEARIC IS.", false}},
        {"22", {"PALAU", false}},
        {"23", {"BLENHEIM REEF", true}},
        {"24", {"BOUVET", false}},
        {"25", {"BRITISH NORTH BORNEO", true}},
        {"26", {"BRITISH SOMALILAND", true}},
        {"27", {"BELARUS", false}},
        {"28", {"CANAL ZONE", true}},
        {"29", {"CANARY IS.", false}},
        {"30", {"CELEBE & MOLUCCA IS.", true}},
        {"31", {"C. KIRIBATI (BRITISH PHOENIX IS.)", false}},
        {"32", {"CEUTA & MELILLA", false}},
        {"33", {"CHAGOS IS.", false}},
        {"34", {"CHATHAM IS.", false}},
        {"35", {"CHRISTMAS I.", false}},
        {"36", {"CLIPPERTON I.", false}},
        {"37", {"COCOS I.", false}},
        {"38", {"COCOS (KEELING) IS.", false}},
        {"39", {"COMOROS", true}},
        {"40", {"CRETE", false}},
        {"41", {"CROZET I.", false}},
        {"42", {"DAMAO, DIU", true}},
        {"43", {"DESECHEO I.", false}},
        {"44", {"DESROCHES", true}},
        {"45", {"DODECANESE", false}},
        {"46", {"EAST MALAYSIA", false}},
        {"47", {"EASTER I.", false}},
        {"48", {"E. KIRIBATI (LINE IS.)", false}},
        {"49", {"EQUATORIAL GUINEA", false}},
        {"50", {"MEXICO", false}},
        {"51", {"ERITREA", false}},
        {"52", {"ESTONIA", false}},
        {"53", {"ETHIOPIA", false}},
        {"54", {"EUROPEAN RUSSIA", false}},
        {"55", {"FARQUHAR", true}},
        {"56", {"FERNANDO DE NORONHA", false}},
        {"57", {"FRENCH EQUATORIAL AFRICA", true}},
        {"58", {"FRENCH INDO-CHINA", true}},
        {"59", {"FRENCH WEST AFRICA", true}},
        {"60", {"BAHAMAS", false}},
        {"61", {"FRANZ JOSEF LAND", false}},
        {"62", {"BARBADOS", false}},
        {"63", {"FRENCH GUIANA", false}},
        {"64", {"BERMUDA", false}},
        {"65", {"BRITISH VIRGIN IS.", false}},
        {"66", {"BELIZE", false}},
        {"67", {"FRENCH INDIA", true}},
        {"68", {"KUWAIT/SAUDI ARABIA NEUTRAL ZONE", true}},
        {"69", {"CAYMAN IS.", false}},
        {"70", {"CUBA", false}},
        {"71", {"GALAPAGOS IS.", false}},
        {"72", {"DOMINICAN REPUBLIC", false}},
        {"74", {"EL SALVADOR", false}},
        {"75", {"GEORGIA", false}},
        {"76", {"GUATEMALA", false}},
        {"77", {"GRENADA", false}},
        {"78", {"HAITI", false}},
        {"79", {"GUADELOUPE", false}},
        {"80", {"HONDURAS", false}},
        {"81", {"GERMANY", true}},
        {"82", {"JAMAICA", false}},
        {"84", {"MARTINIQUE", false}},
        {"85", {"BONAIRE, CURACAO", true}},
        {"86", {"NICARAGUA", false}},
        {"88", {"PANAMA", false}},
        {"89", {"TURKS & CAICOS IS.", false}},
        {"90", {"TRINIDAD & TOBAGO", false}},
        {"91", {"ARUBA", false}},
        {"93", {"GEYSER REEF", true}},
        {"94", {"ANTIGUA & BARBUDA", false}},
        {"95", {"DOMINICA", false}},
        {"96", {"MONTSERRAT", false}},
        {"97", {"ST. LUCIA", false}},
        {"98", {"ST. VINCENT", false}},
        {"99", {"GLORIOSO IS.", false}},
        {"100", {"ARGENTINA", false}},
        {"101", {"GOA", true}},
        {"102", {"GOLD COAST, TOGOLAND", true}},
        {"103", {"GUAM", false}},
        {"104", {"BOLIVIA", false}},
        {"105", {"GUANTANAMO BAY", false}},
        {"106", {"GUERNSEY", false}},
        {"107", {"GUINEA", false}},
        {"108", {"BRAZIL", false}},
        {"109", {"GUINEA-BISSAU", false}},
        {"110", {"HAWAII", false}},
        {"111", {"HEARD I.", false}},
        {"112", {"CHILE", false}},
        {"113", {"IFNI", true}},
        {"114", {"ISLE OF MAN", false}},
        {"115", {"ITALIAN SOMALILAND", true}},
        {"116", {"COLOMBIA", false}},
        {"117", {"ITU HQ", false}},
        {"118", {"JAN MAYEN", false}},
        {"119", {"JAVA", true}},
        {"120", {"ECUADOR", false}},
        {"122", {"JERSEY", false}},
        {"123", {"JOHNSTON I.", false}},
        {"124", {"JUAN DE NOVA, EUROPA", false}},
        {"125", {"JUAN FERNANDEZ IS.", false}},
        {"126", {"KALININGRAD", false}},
        {"127", {"KAMARAN IS.", true}},
        {"128", {"KARELO-FINNISH REPUBLIC", true}},
        {"129", {"GUYANA", false}},
        {"130", {"KAZAKHSTAN", false}},
        {"131", {"KERGUELEN IS.", false}},
        {"132", {"PARAGUAY", false}},
        {"133", {"KERMADEC IS.", false}},
        {"134", {"KINGMAN REEF", true}},
        {"135", {"KYRGYZSTAN", false}},
        {"136", {"PERU", false}},
        {"137", {"REPUBLIC OF KOREA", false}},
        {"138", {"KURE I.", false}},
        {"139", {"KURIA MURIA I.", true}},
        {"140", {"SURINAME", false}},
        {"141", {"FALKLAND IS.", false}},
        {"142", {"LAKSHADWEEP IS.", false}},
        {"143", {"LAOS", false}},
        {"144", {"URUGUAY", false}},
        {"145", {"LATVIA", false}},
        {"146", {"LITHUANIA", false}},
        {"147", {"LORD HOWE I.", false}},
        {"148", {"VENEZUELA", false}},
        {"149", {"AZORES", false}},
        {"150", {"AUSTRALIA", false}},
        {"151", {"MALYJ VYSOTSKIJ I.", true}},
        {"152", {"MACAO", false}},
        {"153", {"MACQUARIE I.", false}},
        {"154", {"YEMEN ARAB REPUBLIC", true}},
        {"155", {"MALAYA", true}},
        {"157", {"NAURU", false}},
        {"158", {"VANUATU", false}},
        {"159", {"MALDIVES", false}},
        {"160", {"TONGA", false}},
        {"161", {"MALPELO I.", false}},
        {"162", {"NEW CALEDONIA", false}},
        {"163", {"PAPUA NEW GUINEA", false}},
        {"164", {"MANCHURIA", true}},
        {"165", {"MAURITIUS", false}},
        {"166", {"MARIANA IS.", false}},
        {"167", {"MARKET REEF", false}},
        {"168", {"MARSHALL IS.", false}},
        {"169", {"MAYOTTE", false}},
        {"170", {"NEW ZEALAND", false}},
        {"171", {"MELLISH REEF", false}},
        {"172", {"PITCAIRN I.", false}},
        {"173", {"MICRONESIA", false}},
        {"174", {"MIDWAY I.", false}},
        {"175", {"FRENCH POLYNESIA", false}},
        {"176", {"FIJI", false}},
        {"177", {"MINAMI TORISHIMA", false}},
        {"178", {"MINERVA REEF", true}},
        {"179", {"MOLDOVA", false}},
        {"180", {"MOUNT ATHOS", false}},
        {"181", {"MOZAMBIQUE", false}},
        {"182", {"NAVASSA I.", false}},
        {"183", {"NETHERLANDS BORNEO", true}},
        {"184", {"NETHERLANDS NEW GUINEA", true}},
        {"185", {"SOLOMON IS.", false}},
        {"186", {"NEWFOUNDLAND, LABRADOR", true}},
        {"187", {"NIGER", false}},
        {"188", {"NIUE", false}},
        {"189", {"NORFOLK I.", false}},
        {"190", {"SAMOA", false}},
        {"191", {"NORTH COOK IS.", false}},
        {"192", {"OGASAWARA", false}},
        {"193", {"OKINAWA (RYUKYU IS.)", true}},
        {"194", {"OKINO TORI-SHIMA", true}},
        {"195", {"ANNOBON I.", false}},
        {"196", {"PALESTINE", true}},
        {"197", {"PALMYRA & JARVIS IS.", false}},
        {"198", {"PAPUA TERRITORY", true}},
        {"199", {"PETER 1 I.", false}},
        {"200", {"PORTUGUESE TIMOR", true}},
        {"201", {"PRINCE EDWARD & MARION IS.", false}},
        {"202", {"PUERTO RICO", false}},
        {"203", {"ANDORRA", false}},
        {"204", {"REVILLAGIGEDO", false}},
        {"205", {"ASCENSION I.", false}},
        {"206", {"AUSTRIA", false}},
        {"207", {"RODRIGUES I.", false}},
        {"208", {"RUANDA-URUNDI", true}},
        {"209", {"BELGIUM", false}},
        {"210", {"SAAR", true}},
        {"211", {"SABLE I.", false}},
        {"212", {"BULGARIA", false}},
        {"213", {"SAINT MARTIN", false}},
        {"214", {"CORSICA", false}},
        {"215", {"CYPRUS", false}},
        {"216", {"SAN ANDRES & PROVIDENCIA", false}},
        {"217", {"SAN FELIX & SAN AMBROSIO", false}},
        {"218", {"CZECHOSLOVAKIA", true}},
        {"219", {"SAO TOME & PRINCIPE", false}},
        {"220", {"SARAWAK", true}},
        {"221", {"DENMARK", false}},
        {"222", {"FAROE IS.", false}},
        {"223", {"ENGLAND", false}},
        {"224", {"FINLAND", false}},
        {"225", {"SARDINIA", false}},
        {"226", {"SAUDI ARABIA/IRAQ NEUTRAL ZONE", true}},
        {"227", {"FRANCE", false}},
        {"228", {"SERRANA BANK & RONCADOR CAY", true}},
        {"229", {"GERMAN DEMOCRATIC REPUBLIC", true}},
        {"230", {"FEDERAL REPUBLIC OF GERMANY", false}},
        {"231", {"SIKKIM", true}},
        {"232", {"SOMALIA", false}},
        {"233", {"GIBRALTAR", false}},
        {"234", {"SOUTH COOK IS.", false}},
        {"235", {"SOUTH GEORGIA I.", false}},
        {"236", {"GREECE", false}},
        {"237", {"GREENLAND", false}},
        {"238", {"SOUTH ORKNEY IS.", false}},
        {"239", {"HUNGARY", false}},
        {"240", {"SOUTH SANDWICH IS.", false}},
        {"241", {"SOUTH SHETLAND IS.", false}},
        {"242", {"ICELAND", false}},
        {"243", {"PEOPLE'S DEMOCRATIC REP. OF YEMEN", true}},
        {"244", {"SOUTHERN SUDAN", true}},
        {"245", {"IRELAND", false}},
        {"246", {"SOVEREIGN MILITARY ORDER OF MALTA", false}},
        {"247", {"SPRATLY IS.", false}},
        {"248", {"ITALY", false}},
        {"249", {"ST. KITTS & NEVIS", false}},
        {"250", {"ST. HELENA", false}},
        {"251", {"LIECHTENSTEIN", false}},
        {"252", {"ST. PAUL I.", false}},
        {"253", {"ST. PETER & ST. PAUL ROCKS", false}},
        {"254", {"LUXEMBOURG", false}},
        {"255", {"ST. MAARTEN, SABA, ST. EUSTATIUS", true}},
        {"256", {"MADEIRA IS.", false}},
        {"257", {"MALTA", false}},
        {"258", {"SUMATRA", true}},
        {"259", {"SVALBARD", false}},
        {"260", {"MONACO", false}},
        {"261", {"SWAN IS.", true}},
        {"262", {"TAJIKISTAN", false}},
        {"263", {"NETHERLANDS", false}},
        {"264", {"TANGIER", true}},
        {"265", {"NORTHERN IRELAND", false}},
        {"266", {"NORWAY", false}},
        {"267", {"TERRITORY OF NEW GUINEA", true}},
        {"268", {"TIBET", true}},
        {"269", {"POLAND", false}},
        {"270", {"TOKELAU IS.", false}},
        {"271", {"TRIESTE", true}},
        {"272", {"PORTUGAL", false}},
        {"273", {"TRINDADE & MARTIM VAZ IS.", false}},
        {"274", {"TRISTAN DA CUNHA & GOUGH I.", false}},
        {"275", {"ROMANIA", false}},
        {"276", {"TROMELIN I.", false}},
        {"277", {"ST. PIERRE & MIQUELON", false}},
        {"278", {"SAN MARINO", false}},
        {"279", {"SCOTLAND", false}},
        {"280", {"TURKMENISTAN", false}},
        {"281", {"SPAIN", false}},
        {"282", {"TUVALU", false}},
        {"283", {"UK SOVEREIGN BASE AREAS ON CYPRUS", false}},
        {"284", {"SWEDEN", false}},
        {"285", {"VIRGIN IS.", false}},
        {"286", {"UGANDA", false}},
        {"287", {"SWITZERLAND", false}},
        {"288", {"UKRAINE", false}},
        {"289", {"UNITED NATIONS HQ", false}},
        {"291", {"UNITED STATES OF AMERICA", false}},
        {"292", {"UZBEKISTAN", false}},
        {"293", {"VIET NAM", false}},
        {"294", {"WALES", false}},
        {"295", {"VATICAN", false}},
        {"296", {"SERBIA", false}},
        {"297", {"WAKE I.", false}},
        {"298", {"WALLIS & FUTUNA IS.", false}},
        {"299", {"WEST MALAYSIA", false}},
        {"301", {"W. KIRIBATI (GILBERT IS. )", false}},
        {"302", {"WESTERN SAHARA", false}},
        {"303", {"WILLIS I.", false}},
        {"304", {"BAHRAIN", false}},
        {"305", {"BANGLADESH", false}},
        {"306", {"BHUTAN", false}},
        {"307", {"ZANZIBAR", true}},
        {"308", {"COSTA RICA", false}},
        {"309", {"MYANMAR", false}},
        {"312", {"CAMBODIA", false}},
        {"315", {"SRI LANKA", false}},
        {"318", {"CHINA", false}},
        {"321", {"HONG KONG", false}},
        {"324", {"INDIA", false}},
        {"327", {"INDONESIA", false}},
        {"330", {"IRAN", false}},
        {"333", {"IRAQ", false}},
        {"336", {"ISRAEL", false}},
        {"339", {"JAPAN", false}},
        {"342", {"JORDAN", false}},
        {"344", {"DEMOCRATIC PEOPLE'S REP. OF KOREA", false}},
        {"345", {"BRUNEI DARUSSALAM", false}},
        {"348", {"KUWAIT", false}},
        {"354", {"LEBANON", false}},
        {"363", {"MONGOLIA", false}},
        {"369", {"NEPAL", false}},
        {"370", {"OMAN", false}},
        {"372", {"PAKISTAN", false}},
        {"375", {"PHILIPPINES", false}},
        {"376", {"QATAR", false}},
        {"378", {"SAUDI ARABIA", false}},
        {"379", {"SEYCHELLES", false}},
        {"381", {"SINGAPORE", false}},
        {"382", {"DJIBOUTI", false}},
        {"384", {"SYRIA", false}},
        {"386", {"TAIWAN", false}},
        {"387", {"THAILAND", false}},
        {"390", {"TURKEY", false}},
        {"391", {"UNITED ARAB EMIRATES", false}},
        {"400", {"ALGERIA", false}},
        {"401", {"ANGOLA", false}},
        {"402", {"BOTSWANA", false}},
        {"404", {"BURUNDI", false}},
        {"406", {"CAMEROON", false}},
        {"408", {"CENTRAL AFRICA", false}},
        {"409", {"CAPE VERDE", false}},
        {"410", {"CHAD", false}},
        {"411", {"COMOROS", false}},
        {"412", {"REPUBLIC OF THE CONGO", false}},
        {"414", {"DEMOCRATIC REPUBLIC OF THE CONGO", false}},
        {"416", {"BENIN", false}},
        {"420", {"GABON", false}},
        {"422", {"THE GAMBIA", false}},
        {"424", {"GHANA", false}},
        {"428", {"COTE D'IVOIRE", false}},
        {"430", {"KENYA", false}},
        {"432", {"LESOTHO", false}},
        {"434", {"LIBERIA", false}},
        {"436", {"LIBYA", false}},
        {"438", {"MADAGASCAR", false}},
        {"440", {"MALAWI", false}},
        {"442", {"MALI", false}},
        {"444", {"MAURITANIA", false}},
        {"446", {"MOROCCO", false}},
        {"450", {"NIGERIA", false}},
        {"452", {"ZIMBABWE", false}},
        {"453", {"REUNION I.", false}},
        {"454", {"RWANDA", false}},
        {"456", {"SENEGAL", false}},
        {"458", {"SIERRA LEONE", false}},
        {"460", {"ROTUMA I.", false}},
        {"462", {"REPUBLIC OF SOUTH AFRICA", false}},
        {"464", {"NAMIBIA", false}},
        {"466", {"SUDAN", false}},
        {"468", {"KINGDOM OF ESWATINI", false}},
        {"470", {"TANZANIA", false}},
        {"474", {"TUNISIA", false}},
        {"478", {"EGYPT", false}},
        {"480", {"BURKINA FASO", false}},
        {"482", {"ZAMBIA", false}},
        {"483", {"TOGO", false}},
        {"488", {"WALVIS BAY", true}},
        {"489", {"CONWAY REEF", false}},
        {"490", {"BANABA I. (OCEAN I.)", false}},
        {"492", {"YEMEN", false}},
        {"493", {"PENGUIN IS.", true}},
        {"497", {"CROATIA", false}},
        {"499", {"SLOVENIA", false}},
        {"501", {"BOSNIA-HERZEGOVINA", false}},
        {"502", {"NORTH MACEDONIA (REPUBLIC OF)", false}},
        {"503", {"CZECH REPUBLIC", false}},
        {"504", {"SLOVAK REPUBLIC", false}},
        {"505", {"PRATAS I.", false}},
        {"506", {"SCARBOROUGH REEF", false}},
        {"507", {"TEMOTU PROVINCE", false}},
        {"508", {"AUSTRAL I.", false}},
        {"509", {"MARQUESAS IS.", false}},
        {"510", {"PALESTINE", false}},
        {"511", {"TIMOR-LESTE", false}},
        {"512", {"CHESTERFIELD IS.", false}},
        {"513", {"DUCIE I.", false}},
        {"514", {"MONTENEGRO", false}},
        {"515", {"SWAINS I.", false}},
        {"516", {"SAINT BARTHELEMY", false}},
        {"517", {"CURACAO", false}},
        {"518", {"SINT MAARTEN", false}},
        {"519", {"SABA & ST. EUSTATIUS", false}},
        {"520", {"BONAIRE", false}},
        {"521", {"SOUTH SUDAN (REPUBLIC OF)", false}},
        {"522", {"REPUBLIC OF KOSOVO", false}},
};
} // namespace ADIF

// clang-format on

#endif // DXCC_MAP_H_GENERATED_H
