#ifndef SUBMODE_MAP_H_GENERATED_H
#define SUBMODE_MAP_H_GENERATED_H

// clang-format off

#include "CaseInsensitiveLess.h"


namespace ADIF {
struct SubmodeEntry {
    std::string parent_mode; // (MODE)
    std::string description; 
};

using SubmodeMap = std::map<std::string, SubmodeEntry, CaseInsensitiveLess>;

/**
 * @brief ADIF Submode to Parent Mode mapping
 */
inline const SubmodeMap SUBMODE_MAP = {
    {"8PSK125", { "PSK", "" } },
    {"8PSK125F", { "PSK", "" } },
    {"8PSK125FL", { "PSK", "" } },
    {"8PSK250", { "PSK", "" } },
    {"8PSK250F", { "PSK", "" } },
    {"8PSK250FL", { "PSK", "" } },
    {"8PSK500", { "PSK", "" } },
    {"8PSK500F", { "PSK", "" } },
    {"8PSK1000", { "PSK", "" } },
    {"8PSK1000F", { "PSK", "" } },
    {"8PSK1200F", { "PSK", "" } },
    {"AMTORFEC", { "TOR", "" } },
    {"ASCI", { "RTTY", "" } },
    {"C4FM", { "DIGITALVOICE", "C4FM 4-level FSK See the Propagation_Mode enumeration section for examples of representing C4FM voice transmissions ." } },
    {"CHIP64", { "CHIP", "" } },
    {"CHIP128", { "CHIP", "" } },
    {"DMR", { "DIGITALVOICE", "Digital Mobile Radio See the Propagation_Mode enumeration section for examples of representing DMR voice transmissions ." } },
    {"DOM-M", { "DOMINO", "" } },
    {"DOM4", { "DOMINO", "" } },
    {"DOM5", { "DOMINO", "" } },
    {"DOM8", { "DOMINO", "" } },
    {"DOM11", { "DOMINO", "" } },
    {"DOM16", { "DOMINO", "" } },
    {"DOM22", { "DOMINO", "" } },
    {"DOM44", { "DOMINO", "" } },
    {"DOM88", { "DOMINO", "" } },
    {"DOMINOEX", { "DOMINO", "" } },
    {"DOMINOF", { "DOMINO", "" } },
    {"DSTAR", { "DIGITALVOICE", "Digital Smart Technologies for Amateur Radio See the Propagation_Mode enumeration section for examples of representing DSTAR voice transmissions ." } },
    {"FMHELL", { "HELL", "" } },
    {"FREEDV", { "DIGITALVOICE", "Digital voice mode for HF radio implemented with open source" } },
    {"FSK31", { "PSK", "" } },
    {"FSKH105", { "HELL", "" } },
    {"FSKH245", { "HELL", "" } },
    {"FSKHELL", { "HELL", "" } },
    {"FSQCALL", { "MFSK", "FSQCall protocol used with FSQ (Fast Simple QSO) transmission mode" } },
    {"FST4", { "MFSK", "This is a digital mode supported by the WSJT-X software" } },
    {"FST4W", { "MFSK", "This is a digital mode supported by the WSJT-X software that is for quasi-beacon transmissions of WSPR-style messages" } },
    {"FT4", { "MFSK", "FT4 is a digital mode designed specifically for radio contesting" } },
    {"GTOR", { "TOR", "" } },
    {"HELL80", { "HELL", "" } },
    {"HELLX5", { "HELL", "" } },
    {"HELLX9", { "HELL", "" } },
    {"HFSK", { "HELL", "" } },
    {"ISCAT-A", { "ISCAT", "" } },
    {"ISCAT-B", { "ISCAT", "" } },
    {"JS8", { "MFSK", "Jordan Sherer designed 8-FSK modulation" } },
    {"JT4A", { "JT4", "" } },
    {"JT4B", { "JT4", "" } },
    {"JT4C", { "JT4", "" } },
    {"JT4D", { "JT4", "" } },
    {"JT4E", { "JT4", "" } },
    {"JT4F", { "JT4", "" } },
    {"JT4G", { "JT4", "" } },
    {"JT9-1", { "JT9", "" } },
    {"JT9-2", { "JT9", "" } },
    {"JT9-5", { "JT9", "" } },
    {"JT9-10", { "JT9", "" } },
    {"JT9-30", { "JT9", "" } },
    {"JT9A", { "JT9", "" } },
    {"JT9B", { "JT9", "" } },
    {"JT9C", { "JT9", "" } },
    {"JT9D", { "JT9", "" } },
    {"JT9E", { "JT9", "" } },
    {"JT9E FAST", { "JT9", "" } },
    {"JT9F", { "JT9", "" } },
    {"JT9F FAST", { "JT9", "" } },
    {"JT9G", { "JT9", "" } },
    {"JT9G FAST", { "JT9", "" } },
    {"JT9H", { "JT9", "" } },
    {"JT9H FAST", { "JT9", "" } },
    {"JT65A", { "JT65", "" } },
    {"JT65B", { "JT65", "" } },
    {"JT65B2", { "JT65", "" } },
    {"JT65C", { "JT65", "" } },
    {"JT65C2", { "JT65", "" } },
    {"JTMS", { "MFSK", "" } },
    {"LSB", { "SSB", "Amplitude modulated voice telephony, lower-sideband, suppressed-carrier" } },
    {"M17", { "DIGITALVOICE", "Digital radio protocol using the Codec 2 voice encoder" } },
    {"MFSK4", { "MFSK", "" } },
    {"MFSK8", { "MFSK", "" } },
    {"MFSK11", { "MFSK", "" } },
    {"MFSK16", { "MFSK", "" } },
    {"MFSK22", { "MFSK", "" } },
    {"MFSK31", { "MFSK", "" } },
    {"MFSK32", { "MFSK", "" } },
    {"MFSK64", { "MFSK", "" } },
    {"MFSK64L", { "MFSK", "" } },
    {"MFSK128", { "MFSK", "" } },
    {"MFSK128L", { "MFSK", "" } },
    {"NAVTEX", { "TOR", "" } },
    {"OLIVIA 4/125", { "OLIVIA", "" } },
    {"OLIVIA 4/250", { "OLIVIA", "" } },
    {"OLIVIA 8/250", { "OLIVIA", "" } },
    {"OLIVIA 8/500", { "OLIVIA", "" } },
    {"OLIVIA 16/500", { "OLIVIA", "" } },
    {"OLIVIA 16/1000", { "OLIVIA", "" } },
    {"OLIVIA 32/1000", { "OLIVIA", "" } },
    {"OPERA-BEACON", { "OPERA", "" } },
    {"OPERA-QSO", { "OPERA", "" } },
    {"PAC2", { "PAC", "" } },
    {"PAC3", { "PAC", "" } },
    {"PAC4", { "PAC", "" } },
    {"PAX2", { "PAX", "" } },
    {"PCW", { "CW", "Coherent CW" } },
    {"PSK10", { "PSK", "" } },
    {"PSK31", { "PSK", "" } },
    {"PSK63", { "PSK", "" } },
    {"PSK63F", { "PSK", "" } },
    {"PSK63RC10", { "PSK", "" } },
    {"PSK63RC20", { "PSK", "" } },
    {"PSK63RC32", { "PSK", "" } },
    {"PSK63RC4", { "PSK", "" } },
    {"PSK63RC5", { "PSK", "" } },
    {"PSK125", { "PSK", "" } },
    {"PSK125RC10", { "PSK", "" } },
    {"PSK125RC12", { "PSK", "" } },
    {"PSK125RC16", { "PSK", "" } },
    {"PSK125RC4", { "PSK", "" } },
    {"PSK125RC5", { "PSK", "" } },
    {"PSK250", { "PSK", "" } },
    {"PSK250RC2", { "PSK", "" } },
    {"PSK250RC3", { "PSK", "" } },
    {"PSK250RC5", { "PSK", "" } },
    {"PSK250RC6", { "PSK", "" } },
    {"PSK250RC7", { "PSK", "" } },
    {"PSK500", { "PSK", "" } },
    {"PSK500RC2", { "PSK", "" } },
    {"PSK500RC3", { "PSK", "" } },
    {"PSK500RC4", { "PSK", "" } },
    {"PSK800RC2", { "PSK", "" } },
    {"PSK1000", { "PSK", "" } },
    {"PSK1000RC2", { "PSK", "" } },
    {"PSKAM10", { "PSK", "" } },
    {"PSKAM31", { "PSK", "" } },
    {"PSKAM50", { "PSK", "" } },
    {"PSKFEC31", { "PSK", "" } },
    {"PSKHELL", { "HELL", "" } },
    {"QPSK31", { "PSK", "" } },
    {"Q65", { "MFSK", "" } },
    {"QPSK63", { "PSK", "" } },
    {"QPSK125", { "PSK", "" } },
    {"QPSK250", { "PSK", "" } },
    {"QPSK500", { "PSK", "" } },
    {"QRA64A", { "QRA64", "" } },
    {"QRA64B", { "QRA64", "" } },
    {"QRA64C", { "QRA64", "" } },
    {"QRA64D", { "QRA64", "" } },
    {"QRA64E", { "QRA64", "" } },
    {"ROS-EME", { "ROS", "" } },
    {"ROS-HF", { "ROS", "" } },
    {"ROS-MF", { "ROS", "" } },
    {"SCAMP_FAST", { "FSK", "SCAMP fast FSK" } },
    {"SCAMP_OO", { "MTONE", "SCAMP single modulated tone on/off keying" } },
    {"SCAMP_OO_SLW", { "MTONE", "SCAMP single modulated tone on/off slow keying" } },
    {"SCAMP_SLOW", { "FSK", "SCAMP slow FSK" } },
    {"SCAMP_VSLOW", { "FSK", "SCAMP very slow FSK" } },
    {"SIM31", { "PSK", "" } },
    {"SITORB", { "TOR", "" } },
    {"SLOWHELL", { "HELL", "" } },
    {"THOR-M", { "THOR", "" } },
    {"THOR4", { "THOR", "" } },
    {"THOR5", { "THOR", "" } },
    {"THOR8", { "THOR", "" } },
    {"THOR11", { "THOR", "" } },
    {"THOR16", { "THOR", "" } },
    {"THOR22", { "THOR", "" } },
    {"THOR25X4", { "THOR", "" } },
    {"THOR50X1", { "THOR", "" } },
    {"THOR50X2", { "THOR", "" } },
    {"THOR100", { "THOR", "" } },
    {"THRBX", { "THRB", "" } },
    {"THRBX1", { "THRB", "" } },
    {"THRBX2", { "THRB", "" } },
    {"THRBX4", { "THRB", "" } },
    {"THROB1", { "THRB", "" } },
    {"THROB2", { "THRB", "" } },
    {"THROB4", { "THRB", "" } },
    {"USB", { "SSB", "Amplitude modulated voice telephony, upper-sideband, suppressed-carrier" } },
    {"VARA HF", { "DYNAMIC", "Channel adaptive high-speed modem for HF" } },
    {"VARA SATELLITE", { "DYNAMIC", "Channel adaptive high-speed modem for satellite operations" } },
    {"VARA FM 1200", { "DYNAMIC", "Channel adaptive high-speed modem for FM transceivers" } },
    {"VARA FM 9600", { "DYNAMIC", "Channel adaptive high-speed modem for FM transceivers" } },
};
} // namespace ADIF

// clang-format on

#endif // SUBMODE_MAP_H_GENERATED_H
