# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ADIF_VOLUME_STRESS: "1"
  # ADIF_EXTREME_TEST: "1"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llxx2013/qt-builder:6.11.0

    defaults:
      run:
        shell: bash -l {0}

    outputs:
      upload_success: ${{ steps.check-status.outputs.upload_success }}

    steps:
      - uses: actions/checkout@v6

      - name: Build & Test
        run: |
          . $ENABLE_GCC_TOOLSET && qt-cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_INSTALL_LIBDIR=lib
          . $ENABLE_GCC_TOOLSET && cmake --build build --parallel
          QT_QPA_PLATFORM=offscreen ctest --test-dir build --output-on-failure --verbose

      - name: Package AppImage
        env:
          VERSION: ${{ github.ref_name }}
          EXTRA_PLATFORM_PLUGINS: "libqwayland.so"
          # EXTRA_QT_MODULES: "waylandcompositor"
        run: |
          DESTDIR=$PWD/AppDir cmake --install build
          if ! command -v tree &> /dev/null; then
            echo "Installing tree..."
            dnf install -y tree
          fi

          linuxdeploy --appdir $PWD/AppDir \
            -d $PWD/linux-deploy/GLogKit.desktop \
            -e $PWD/AppDir/usr/bin/GLogKit \
            -i $PWD/linux-deploy/GLogKit.png \
            --plugin=qt 

          echo "Processing translations..."
          TRANS_DIR="$PWD/AppDir/usr/translations"
          if [ -d "$TRANS_DIR" ]; then
              pushd "$TRANS_DIR" > /dev/null
              for qt_file in qt_*.qm; do
                  if [ ! -f "$qt_file" ]; then
                      continue
                  fi
                  lang_suffix="${qt_file#qt_}"
                  lang="${lang_suffix%.qm}"
                  base_file="qtbase_${lang}.qm"
                  if [ -e "$base_file" ] || [ -L "$base_file" ]; then
                      echo "Linking $base_file -> $qt_file"
                      ln -sf "$qt_file" "$base_file"
                  fi
                  decl_file="qtdeclarative_${lang}.qm"
                  if [ -e "$decl_file" ] || [ -L "$decl_file" ]; then
                      echo "Linking $decl_file -> $qt_file"
                      ln -sf "$qt_file" "$decl_file"
                  fi
              done
              popd > /dev/null
          fi

          echo "--- AppDir Structure ---"
          tree $PWD/AppDir -L 4

          linuxdeploy --appdir $PWD/AppDir --output appimage

          APPIMAGE_BIN=$(ls GLogKit-*.AppImage | head -n 1)
          TAR_NAME="${APPIMAGE_BIN%.AppImage}.tar.xz"
          tar -cJf "$TAR_NAME" -C "$PWD/AppDir" .

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v7
        id: upload-linux
        continue-on-error: true
        with:
          name: Linux-Deploy
          retention-days: 5
          path: |
            ./*.AppImage
            ./*.tar.xz
          compression-level: 0
      
      - name: Check Upload Status
        id: check-status
        run: |
          if [ "${{ steps.upload-linux.outcome }}" == "failure" ]; then
            echo "upload_success=false" >> $GITHUB_OUTPUT
          else
            echo "upload_success=true" >> $GITHUB_OUTPUT
          fi

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Tools
        run: choco install winflexbison3 nsis -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: 'true'
          # modules: 'qtcharts'

      - name: Setup Environment
        shell: pwsh
        run: |
          echo "C:\Program Files (x86)\NSIS" >> $GITHUB_PATH
          ls "C:\ProgramData\chocolatey\lib\winflexbison3\tools\"
          ls "C:\Program Files (x86)\NSIS"
          ls "C:\ProgramData\chocolatey\lib\nsis"

      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DFLEX_INCLUDE_DIRS="C:\ProgramData\chocolatey\lib\winflexbison3\tools"

      - name: Build & Test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --build build --config Release --parallel
          cd build
          ctest -C Release --output-on-failure --verbose

      - name: Install, Compress and Generate NSIS
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

          cmake --install build --prefix C:/AppDir
          echo --- AppDir Structure ---
          dir /s C:\AppDir

          set "VERSION=${{ github.ref_name }}"
          set "ZIP_NAME=GLogKit-%VERSION%-windows-x64.zip"
          set "EXE_NAME=GLogKit-%VERSION%-Installer-x64.exe"

          powershell -Command "Compress-Archive -Path C:\AppDir\* -DestinationPath %ZIP_NAME% -Force"

          (
            echo !include "MUI2.nsh"
            echo Name "GLogKit %VERSION%"
            echo OutFile "%EXE_NAME%"
            echo InstallDir "$PROGRAMFILES64\GLogKit"
            echo RequestExecutionLevel admin
            echo !insertmacro MUI_PAGE_WELCOME
            echo !insertmacro MUI_PAGE_DIRECTORY
            echo !insertmacro MUI_PAGE_INSTFILES
            echo !insertmacro MUI_PAGE_FINISH
            echo !insertmacro MUI_UNPAGE_CONFIRM
            echo !insertmacro MUI_UNPAGE_INSTFILES
            echo !insertmacro MUI_LANGUAGE "English"
            echo Section "MainSection" SEC01
            echo   SetOutPath "$INSTDIR"
            echo   File /r "C:\AppDir\*"
            echo   CreateShortCut "$SMPROGRAMS\GLogKit.lnk" "$INSTDIR\bin\GLogKit.exe"
            echo   WriteUninstaller "$INSTDIR\Uninstall.exe"
            echo SectionEnd
            echo Section "Uninstall"
            echo   Delete "$SMPROGRAMS\GLogKit.lnk"
            echo   RMDir /r "$INSTDIR"
            echo SectionEnd
          ) > installer.nsi

          "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v7
        continue-on-error: true
        with:
          name: Windows-Deploy
          retention-days: 5
          path: |
            ./*.zip
            ./*.exe

  build-macos:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup ENV
        run: |
          brew install bison flex ccache lld
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm@20)/bin/" >> $GITHUB_PATH

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.3'
          host: 'mac'
          target: 'desktop'
          cache: 'true'
          # modules: 'qtcharts'

      - name: Configure CMake
        run: |
          export FLEX_INCLUDE_DIRS="$(brew --prefix flex)/include"
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=$Qt6_DIR \
            -DCMAKE_INSTALL_PREFIX=/Applications \
            -DFLEX_INCLUDE_DIRS="$FLEX_INCLUDE_DIRS" \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"

      - name: Build & Test
        run: |
          cmake --build build --config Release -j4
          cd build
          ctest -C Release --output-on-failure --verbose

      - name: Install & Deploy
        run: |
          DESTDIR=$PWD/deploy_out cmake --install build --config Release
          find deploy_out/Applications -name "libqsqlmimer.dylib" -delete
          
          APP_PATH=$(find deploy_out/Applications -name "*.app" -type d -maxdepth 3 | head -n 1)
          echo "Found App Bundle: $APP_PATH"
          if ! command -v tree &> /dev/null; then
            brew install tree
          fi
          echo "--- Applications Structure ---"
          tree deploy_out/Applications -L 5
          otool -L deploy_out/Applications/GLogKit.app/Contents/MacOS/GLogKit
          otool -L deploy_out/Applications/SDK/GLogKitCore.framework/GLogKitCore
          tar -cJf "GLogKit-${{ github.ref_name }}-macOS.tar.xz" -C deploy_out Applications
          DMG_NAME="GLogKit-${{ github.ref_name }}-macOS.dmg"
          ln -s /Applications deploy_out/Applications/Applications
          hdiutil create -volname "GLogKit" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_NAME"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        continue-on-error: true
        with:
          name: MacOS-Deploy
          retention-days: 5
          path: | 
            ./*.dmg
            ./*.tar.xz

  release:
    name: Create Release
    needs: [build-linux, build-windows, build-macos]
    if: |
      always() &&
      startsWith(github.ref, 'refs/tags/v') &&
      needs.build-linux.outputs.upload_success == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts/
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/*.AppImage
            ./artifacts/*.zip
            ./artifacts/*.dmg
            ./artifacts/*.tar.xz
            ./artifacts/*.exe
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'dev') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}